import {
    Users,
    FolderKanban,
    ListChecks,
    FileText,
    Settings,
    LayoutDashboard,
    CreditCard,
    Briefcase,
    Calendar,
    MessageSquare,
    BarChart3,
    Archive,
    ChevronLeft,
    ChevronRight,
} from "lucide-react";

export const iconMap: Record<string, any> = {
    clientes: Users,
    projetos: FolderKanban,
    tarefas: ListChecks,
    arquivos: FileText,
    configuracoes: Settings,
    dashboard: LayoutDashboard,
    financeiro: CreditCard,
    contratos: Briefcase,
    calendario: Calendar,
    mensagens: MessageSquare,
    relatorios: BarChart3,
    arquivados: Archive,
};